# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PculYUOxUSuH37j36PxaMBmczk2xKgj_
"""

import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# --- Nama Kelas Sesuai Folder Dataset ---
class_names = [
    'Belimbing Wuluh', 'Jambu Biji', 'Jeruk Nipis', 'Kemangi',
    'Lidah Buaya', 'Nangka', 'Pandan', 'Pepaya', 'Seledri', 'Sirih'
]

# --- Khasiat Sesuai Daun ---
khasiat_daun = {
    'Belimbing Wuluh': 'Menurunkan tekanan darah, mengatasi batuk, dan digunakan sebagai antiseptik alami.',
    'Jambu Biji': 'Mengatasi diare, mempercepat penyembuhan luka, dan menjaga kesehatan jantung.',
    'Jeruk Nipis': 'Meningkatkan daya tahan tubuh, melancarkan pencernaan, dan membantu detoksifikasi.',
    'Kemangi': 'Menambah nafsu makan, memiliki sifat antibakteri, dan meredakan stres.',
    'Lidah Buaya': 'Menyembuhkan luka bakar, melembapkan kulit, dan menutrisi rambut.',
    'Nangka': 'Sumber energi, mendukung pencernaan, dan mengandung antioksidan alami.',
    'Pandan': 'Menambah aroma masakan, menurunkan tekanan darah, dan sebagai penenang alami.',
    'Pepaya': 'Melancarkan pencernaan, meningkatkan trombosit, dan bersifat anti-kanker.',
    'Seledri': 'Menurunkan tekanan darah, membantu detoksifikasi, dan mengandung antioksidan.',
    'Sirih': 'Antiseptik alami, menghentikan pendarahan ringan, dan menjaga kesehatan mulut.'
}

# --- Load Model ---
@st.cache_resource
def load_model():
    return tf.keras.models.load_model('mobilenetv22_model.h5')

# --- Preprocessing dan Prediksi ---
def preprocess_and_predict(model, image):
    if image.mode != 'RGB':
        image = image.convert('RGB')
    image = image.resize((224, 224))
    image_array = np.expand_dims(np.array(image), axis=0)
    processed = preprocess_input(image_array)
    prediction = model.predict(processed)
    idx = np.argmax(prediction)
    confidence = np.max(prediction) * 100
    return class_names[idx], confidence

# --- UI ---
st.set_page_config(page_title="Klasifikasi Daun Herbal", layout="centered")
st.markdown("<h3 style='text-align: center;'><span style='color:#0abf53;'>CARI</span> TANAMAN HERBAL<br><span style='color:#1abc9c;'>DENGAN</span> SATU KLIK!!</h3>", unsafe_allow_html=True)
st.markdown("---")

uploaded_file = st.file_uploader("Unggah gambar daun", type=["jpg", "jpeg", "png"])

model = load_model()

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Gambar Daun yang Diunggah", use_column_width=True)
    with st.spinner("Menganalisis gambar..."):
        predicted_class, confidence = preprocess_and_predict(model, image)
        manfaat = khasiat_daun.get(predicted_class, "Khasiat tidak ditemukan.")

    st.markdown("---")
    st.markdown(f"<p style='text-align:center; font-size:24px; color:#0abf53;'><strong>{predicted_class}</strong></p>", unsafe_allow_html=True)
    st.markdown(f"<p style='text-align:center; font-size:16px;'>Tingkat Keyakinan: <strong>{confidence:.2f}%</strong></p>", unsafe_allow_html=True)
    st.markdown(f"<p style='text-align:center; font-size:18px; color:#444; border-left: 4px solid #0abf53; padding-left: 10px;'><strong>Khasiat:</strong> {manfaat}</p>", unsafe_allow_html=True)
else:
    st.info("Silakan unggah gambar daun terlebih dahulu.")

# --- Footer ---
st.markdown("<br><br><br>", unsafe_allow_html=True)
st.markdown("---")
col1, col2, col3, col4, col5 = st.columns(5)
with col2:
    st.markdown('<div style="text-align:center;"><img src="https://img.icons8.com/ios/50/00e676/camera--v1.png" width="40"/></div>', unsafe_allow_html=True)
with col4:
    st.markdown('<div style="text-align:center;"><img src="https://img.icons8.com/ios/50/00e676/image.png" width="40"/></div>', unsafe_allow_html=True)